


baseurl = "https://pinkowl.github.io"
languageCode = "en-us"
title = "Pink Owl Design"
#theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Pink Owl Design"
	description = "Bespoke Cakes and Graphic Design"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Hugo Creative Theme"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Pink Owl Design"
		subtitle   = "Where our passion for stunning, delicious bespoke cakes and cupcakes comes together with amazing and creative graphic design solutions for your needs"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "Need a cake for that special birthday? New logo for your business? Delicious cupcakes for that babyshower? Birthday invitations? Image editing? Wedding stationary? We have got you covered! "
		#buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Here to help you!"

        [[params.services.list]]
            icon = "fa-twitter"
            title = "Follow us on Twitter at Pink_Owl_Design"
            description = "New content posted regularly showcasing new designs"

        [[params.services.list]]
			icon = "fa-behance"
			title = "Behance Portfolio"
			description = "Check out Behance for a more extensive portfolio of our works"

		[[params.services.list]]
            icon = "fa-smile"
            title = "Great customer service"
            description = "Attention to detail sets us apart"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Love"
            description = "Personal creations for you"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		#headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			#text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? Want a gorgeous cake for that special occasion? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+44 00 7522714015"
		email = "pinkowl_design@outlook.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""

